#+title: 简短博文

#+hugo_base_dir: ~/Data/Pilrymage/blog/
#+hugo_section: post
#+hugo_auto_set_lastmod: t
* TODO Test :tag1:@category1:
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: my-third-post
:EXPORT_FILE_NAME: index
:END:
** 有一说一
Emacs是世界上最好的编辑器！
#+begin_src C
#include<stdio.h>
int main()
  {
    printf("Hello, world!");
    return 0;
  }
#+end_src


* DONE Emacs 搭配 Hugo 的个人博客创作    :Emacs:@Lisp与Emacs:
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: emacs-with-hugo-blog
:EXPORT_FILE_NAME: index
:END:
参见：[[https://zilongshanren.com/post/move-from-hexo-to-hugo/][子龙山人]]，[[https://emacs-china.org/t/topic/5427][Emacs 中文社区串]]

作为一款文本编辑器，Emacs 的上限是肉眼可见的极高：定制水平很大程度上影响了编辑器的外观及能力。

上一次 Emacs 让我为之惊叹的是即使是在终端的输入，而内置的输入法真的也能在其中运作！
当然是因为 Emacs 的 TUI（终端界面）是通过GUI渲染的，然而这就能给终端赋以超越 vim 的能量。
vim 并非不能使用内置输入法，然而 Emacs 才是为大而全的应用而生，在ipad的终端里写文章不再是梦。

或许这也让我这个 Emacs 新人对 Emacs 狂热粉多了一分感同身受吧。爱好 Emacs 的大多是非常看重自己工具流的定制化。
因而当我找到一套适用于 org mode 的博客生成方案时，我不禁再次对 Emacs 社区的大佬们肃然起敬。

** 什么是 Org mode?
Org mode 是一个同 Emacs 绑定的软件包，也指这个软件包所操作的标记文本： org 文件。

可以用 markdown 文件来类比 org 文件， org 就是 organization （组织）。
markdown 文件有 Typora、 Notion 等等编辑器，将其渲染成网页上展示的形式。

而 org 文件主要跟 Emacs 一起使用，拜 Emacs 的海量文本编辑功能所赐，
org 的编辑器非市面上任何一款编辑器所能比拟。
比如直接从文本生成博客，敢问其它编辑器做得到吗？！

** 博客搭建
参见：[[https://gohugo.io/getting-started/quick-start/][Hugo quickstart]]、and [[HTTPs://gohugo.io/hosting-and-deployment/hosting-on-github/][Host on Github]]

Hugo 搭建非常快捷。上次尝试搭建博客还是在 Windows 上用 Hexo ，在 Github Pages 发布上要死要活。
这次跟着教程，花个 5 分钟就能开本地服务器了。 Github Page 也有适用于 Hugo 的 Action。

绑定个人域名有点麻烦，要在 DNS 提供商引导一个 CNAME 记录，
闲话一句，这也是我没用 Netlify 的原因，因为在应用里添加不上域名，显示已被占用，
它大概要让我把 DNS 记录全迁移到 Netlify 自己的服务器才行。（是我哪里弄错了吗？）

Github Actions 就是一个持续集成（CI），对新人而言最大的优势就是仓库也是 Github 的。
这之后只需 git push 就能更新博客，剩下的已经自动化。
** Emacs 与 Hugo 导出功能
参见：[[https://ox-hugo.scripter.co/doc/quick-start/][ox-hugo quickstart]].
Hugo 支持 org 格式作为博文，然而其渲染支持不比其 markdown 渲染器好。
更优的做法是让 Emacs 将 org 格式转化为 md 格式， 然后交给 hugo。
这里使用 Emacs 的 ox-hugo 包实现转化。

*** 安装
doom emacs 的 package.el：
#+begin_src emacs-lisp
(package! ox-hugo)
#+end_src

*** 配置
用 ~#+hugo_base_dir~ 指定 hugo 的根目录
默认的主题，ox-hugo会直接把 md 文件生成在 content/posts 里，可以直接跳到下一节。
如果你用的主题使用了不同的目录以及 Hugo 的 [[https://gohugo.io/content-management/page-bundles/][Page Bundle]], 如[[https://stack.jimmycai.com/writing/markdown][stack]]主题，
可以用 ~#+hugo_section: post~ 指定博文放在 content/post 里，
用 ~:EXPORT_HUGO_BUNDLE: my-first-blog~ 与 ~#+export_file_name: index~
形成一个名为 my-fist-blog 的文件夹，包含正文部分的 index.md 。

*** 导出
使用 ~org-hugo-export-wim-to-md~ 函数导出。该函数有快捷键，但是与 doom emacs 不兼容。
因为 org 的 todo 对应 hugo 的 draft 状态，只有先将博文设为 done 才能导出。
然后就可以用 ~hugo server~ 检查输出了。
** 结语
写个五分钟，这篇博文就已经部署好了，咱充分享受到科技的便利。
其实这篇也没有什么自己的东西，只是不完整地总结了一边前人的知识。
然而比之以前用 Windows 的 Git 命令行强行部署 hexo ，半懂不懂，个人觉得算是巨大的进步了。

学计算机的，果然还是要有一个 Linux 系统，免去众多的闲杂烦恼。
而遇见 Emacs， 虽说是学 Linux 的附带收获，却实在是我的一大幸事，它能不断满足我的奇妙想法。

* TODO 4chan：互联网的遗民
** 快速FAQ

A：为什么写这么一个博文？

Q：因为国内没什么人看4chan。这也就是一篇安利文吧。
可能大多数中文论坛，谈及4chan 的就是“臭名昭著的粪坑”，
或者是“网络暴力的根据地”；时不时也能看到几篇黑色幽默的“4chan笑话”。
用国内论坛类比，其形式为中国的“A岛匿名版”所借鉴；
然而就内容而言，其实更接近百度贴吧；包罗万象，有不少精品贴与亚文化，
除了4chan没有用户账户，人人都是anon（匿名者，anonymous)。

我喜欢百度贴吧，至少是以前的；五湖四海的网民们热心总结资源与教程，
相互之间谈天说地，或体现出每个人的人生轨迹，
堪称是中国互联网文化与精神的范本。
不论其中糟粕，贴吧也曾让我有所收获；
而接触 4chan 同样让我是收获满满。因此我希望写篇介绍文。

A：4chan 用户都是些什么人？
Q：不需统计，其用户画像多为英语圈的美国白人。
再加一条，就是用户多宅男。/a/（动漫版）是此处最大的版块。
总之，用户大约是歧视链的顶端，鄙视链的底端（weaboo）。
如果你混二次元，先补几部番能更好地理解 4chan，
虽说这里的用户是婆罗门扎堆。

** 翻遍小网站，你能得到什么
*** /a/ Anime
动画版，与动漫相关的各种东西。
然而并没有很多子版块，虽然其它版块普遍有大量子版块。

梦开始的地方。从中甚至产生了一部同人 Galgame。

*** /g/ Technology
科技版，实际上其内容面向程序员群体。
这一版块的用户鱼龙混杂，涉猎广泛，有各种常驻子版块：
- /dpt/：Daily Programming Thread，编程日常串。
- /fwt/：Friendly Windows Thread, 友好 Windows 串，
- /fglt/：Friendly GNU/Linux Thread, 友好 GNU/Linux 串，
- /flet/：Friendly Lisp & Emacs Thread，Lisp 与 Emacs 串，
  总有各种 SICP 的 meme 图。
- /csg/：Chink Shit General，国货垃圾佬综合。
- /pcbg/：PC Building General，电脑拼装综合。
- /wsg/：Home Server General，自建服务器综合。
- /hsg/：Home Server General，自建服务器综合。
- /ptg/：Private Tracker General，PT 综合。
- /psg/：Privacy & Security General，隐私与安全综合。
- /dmp/：Digital Music Production，电音制作。

一些紧跟热点的子版块：
- /aicg/：AI chatbot general，AI 聊天机器人综合。
- /sdg/：Stable Diffusion general，Stable Diffusion 综合。
- /vsg/：AI Voice Synthesis General，AI 语音合成综合。

以及一些产品的推荐：
- /tpg/：ThinkPad General，ThinkPad 天下第一！
- /iemg/：
- /ppg/：Pen & Pencil General，笔与铅笔综合。

值得注意的是，其子版块的一楼（sticky）总有很多免费资源供下载学习。
 /g/ 的置顶MOD串放出了/g/的维基，从而/g/也是 Gentoo Linux 的意思。
 置顶还有三个人的“神像”：
 TempleOS 作者特伦斯・A・戴维斯(TAD)
 《珈百璃的堕落》里[[][“看不起苹果粉”]]的萨塔妮亚(SKM)
 GNU自由软件运动的理查德・M・斯托曼(RMS)，

*** /jp/
"get out of /jp/."（魔理沙）

日本版，包括势力很大的东方众，龙骑士作品讨论，型月，
日本偶像、综艺、地铁以及niconico与音MAD等等。
*** /pol/ Politically *Incorrect*
政治不正确版。用户多右派。
*** /lit/ Literature
文学版。有各种书单推荐，包括古代语言学习。
*** /tg/ Traditional Games
传统游戏版。包括绘画，写故事，下棋等消遣。


* TODO vim：千斤顶
* TODO 看山不是山：解构方法用于任意一门学科的学习
** 序
简而言之：

看山是山是建构；

看山不是山是解构；

看山又是山是重构。

第一句的山是个概念或者是个表面，而第三句的山则是个系统。

——知乎用户“螺旋真理”在“如何理解「看山是山，看山不是山，看山还是山」的三层境界？”下的回答

** 认识一个学科的过程与后现代话术

一个人的学习一门课程的过程，同时是其一生求学十数年的缩影；
义务教育阶段给予人以基本的三观理性与社会运作的逻辑，此时由家长与老师耳提面命的指导；
大学则给予人审视反思自己所学的批判性思维，对自己身边的一切有所怀疑与思考；
而博士以及更深的研究者将会在一个方向上尝试用理性胶粘起众多的知识，
形成自己的“脚手架”，其百尺竿头者最终会为学科的大厦上添砖加瓦，更进一步。

从小学到博士，二十多年时间，耗费精力甚巨。
幸而我们暂且不需批判教材知识，更不急着投身学科建设。
然而我意识到，学习一个学科，总是可以用所谓“建构－解构－重构”的方法来深入。
要而言之，就是“螺旋式上升”的认知吧。

*** 感性认识

*** 打倒感性认识
* TODO Windows 重装扩C盘的故事，以及Archlinux 重装 grub 引导
** Windows 一事
我的电脑是 Windows + Arch 双系统。
某次抱怨 Windows 的 C 盘只有 60G 容量太小，分给 D 盘的空间太大，
于是果断删 D 盘，C 盘大大扩张。
———话说一个电脑分两个盘是好习惯，这样重装 C 盘系统就不用搬运 D 盘资料，
当然我是外挂了一个固态硬盘做资料盘。
———结果不知如何，电脑的管理员权限挂掉了。
可能也与我之前把一些环境变量写到 D 盘有关系。

由于大多数上次重装时软件都放在了 D盘，现在则是完全用不了。
用不了管理员权限，连rufus也用不了，也烧录不了重装盘。
幸好进入安全模式还能用管理员权限，还是老老实实地重装了系统。
这时候外挂硬盘的优势就十分明显了：重装后可以用里面的便携版本软件。

** Archlinux 的抱怨
重装还好，结果重新启动，就不由分说的入了 ~grub rescue~ 。
好家伙，Windows 的事，grub 搀和什么？这也只能再烧一个 Archiso 盘来救场。

*** btrfs
照着 [[][archlinux 简明指南]]做的 btrfs 文件系统，回滚非常好用而不怎么要操心。
然而挂载就费点力了，主要单受过安利而没读过 btrfs 文档，而挂载又有一堆选项。
幸好第一轮折腾没有出事，老老实实找到指南来挂载。
ext4 的挂载要容易挺多。。。

*** /boot/efi 挂载一事
记不清是要把 EFI 分区挂在 /boot 还是 /boot/efi 了，也因此栽了大坑。
现在稍微明白一点 grub 加载 efi 的道理了：安装 linux 内核会把 img 文件放在在 /boot 里，
而 ~grub-mkconfig~ 会寻找这些 img 文件，做成 menuentry 项。
至于不会自动放出引导文件的系统，如 Windows，
有 os-prober 在 EFI 分区里寻找引导文件，Windows 就是efimgfw.efi。
我的EFI分区挂载在 /boot/efi，有子目录 /boot/efi/EFI 包含 Windows 等系统的引导文件。

一个坑是，指南说用 Windows 自己建的 EFI 分区，又说用 /boot 直接做启动分区挂载点，
结果 Windows 的分区默认 100M 大小，有时候 grub 装不进，有时候 linux 的 img 文件装不进。
用 /boot/efi 挂载， linux 的 img 文件装在 /boot 下，实际上是根目录（主分区）的一部分，这就装得下了。

os-prober 由于某种原因，报错 ~error mkdir /var/lock/dmraid/~ ，然后检测不到 Windows。
我没有头绪；有几个贴子说是自己的 fstab 没更新，挂载不对。
我最后直接手写 grub.cfg 文件了。就是要找到上面所说的 efimgfw.efi。

想通这一点大约折腾了一晚上4个小时加早上2小时。

*** fstab 与自动挂载
一个小知识，因为 /etc/fstab 也重做了，结果外挂的硬盘不见了。
要自动挂载也非常容易： ~blkid /etc/<编号>~ 导入 /etc/fstab，
然后保留UUID，格式与其它行相同即可。
一个 ntfs 格式的外挂硬盘，可以同时用于 Windows 与 Archlinux 双系统的资源共享。
不过主要是 Archlinux 可以直接访问 Windows 的全部内容，Windows 和 ext4 不太对付。。。

** 最后
照着教程装好的 Archlinux ，大约不能表示自己多么擅长 linux 。
一些小事故，足以让人看到自己和 linux 运维的水平差异。。。
