#+title: 简短博文

#+hugo_base_dir: ~/Data/Pilrymage/blog/
#+hugo_section: post
#+hugo_auto_set_lastmod: t
* TODO Test :tag1:@category1:
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: my-third-post
:EXPORT_FILE_NAME: index
:END:
** 有一说一
Emacs是世界上最好的编辑器！
#+begin_src C
#include<stdio.h>
int main()
  {
    printf("Hello, world!");
    return 0;
  }
#+end_src


* DONE Emacs 搭配 Hugo 的个人博客创作    :Emacs:@Lisp与Emacs:
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: emacs-with-hugo-blog
:EXPORT_FILE_NAME: index
:END:
参见：[[https://zilongshanren.com/post/move-from-hexo-to-hugo/][子龙山人]]，[[https://emacs-china.org/t/topic/5427][Emacs 中文社区串]]

作为一款文本编辑器，Emacs 的上限是肉眼可见的极高：定制水平很大程度上影响了编辑器的外观及能力。

上一次 Emacs 让我为之惊叹的是即使是在终端的输入，而内置的输入法真的也能在其中运作！
当然是因为 Emacs 的 TUI（终端界面）是通过GUI渲染的，然而这就能给终端赋以超越 vim 的能量。
vim 并非不能使用内置输入法，然而 Emacs 才是为大而全的应用而生，在ipad的终端里写文章不再是梦。

或许这也让我这个 Emacs 新人对 Emacs 狂热粉多了一分感同身受吧。爱好 Emacs 的大多是非常看重自己工具流的定制化。
因而当我找到一套适用于 org mode 的博客生成方案时，我不禁再次对 Emacs 社区的大佬们肃然起敬。

** 什么是 Org mode?
Org mode 是一个同 Emacs 绑定的软件包，也指这个软件包所操作的标记文本： org 文件。

可以用 markdown 文件来类比 org 文件， org 就是 organization （组织）。
markdown 文件有 Typora、 Notion 等等编辑器，将其渲染成网页上展示的形式。

而 org 文件主要跟 Emacs 一起使用，拜 Emacs 的海量文本编辑功能所赐，
org 的编辑器非市面上任何一款编辑器所能比拟。
比如直接从文本生成博客，敢问其它编辑器做得到吗？！

** 博客搭建
参见：[[https://gohugo.io/getting-started/quick-start/][Hugo quickstart]]、and [[HTTPs://gohugo.io/hosting-and-deployment/hosting-on-github/][Host on Github]]

Hugo 搭建非常快捷。上次尝试搭建博客还是在 Windows 上用 Hexo ，在 Github Pages 发布上要死要活。
这次跟着教程，花个 5 分钟就能开本地服务器了。 Github Page 也有适用于 Hugo 的 Action。

绑定个人域名有点麻烦，要在 DNS 提供商引导一个 CNAME 记录，
闲话一句，这也是我没用 Netlify 的原因，因为在应用里添加不上域名，显示已被占用，
它大概要让我把 DNS 记录全迁移到 Netlify 自己的服务器才行。（是我哪里弄错了吗？）

Github Actions 就是一个持续集成（CI），对新人而言最大的优势就是仓库也是 Github 的。
这之后只需 git push 就能更新博客，剩下的已经自动化。
** Emacs 与 Hugo 导出功能
参见：[[https://ox-hugo.scripter.co/doc/quick-start/][ox-hugo quickstart]].
Hugo 支持 org 格式作为博文，然而其渲染支持不比其 markdown 渲染器好。
更优的做法是让 Emacs 将 org 格式转化为 md 格式， 然后交给 hugo。
这里使用 Emacs 的 ox-hugo 包实现转化。

*** 安装
doom emacs 的 package.el：
#+begin_src emacs-lisp
(package! ox-hugo)
#+end_src

*** 配置
用 ~#+hugo_base_dir~ 指定 hugo 的根目录
默认的主题，ox-hugo会直接把 md 文件生成在 content/posts 里，可以直接跳到下一节。
如果你用的主题使用了不同的目录以及 Hugo 的 [[https://gohugo.io/content-management/page-bundles/][Page Bundle]], 如[[https://stack.jimmycai.com/writing/markdown][stack]]主题，
可以用 ~#+hugo_section: post~ 指定博文放在 content/post 里，
用 ~:EXPORT_HUGO_BUNDLE: my-first-blog~ 与 ~#+export_file_name: index~
形成一个名为 my-fist-blog 的文件夹，包含正文部分的 index.md 。

*** 导出
使用 ~org-hugo-export-wim-to-md~ 函数导出。该函数有快捷键，但是与 doom emacs 不兼容。
因为 org 的 todo 对应 hugo 的 draft 状态，只有先将博文设为 done 才能导出。
然后就可以用 ~hugo server~ 检查输出了。
** 结语
写个五分钟，这篇博文就已经部署好了，咱充分享受到科技的便利。
其实这篇也没有什么自己的东西，只是不完整地总结了一边前人的知识。
然而比之以前用 Windows 的 Git 命令行强行部署 hexo ，半懂不懂，个人觉得算是巨大的进步了。

学计算机的，果然还是要有一个 Linux 系统，免去众多的闲杂烦恼。
而遇见 Emacs， 虽说是学 Linux 的附带收获，却实在是我的一大幸事，它能不断满足我的奇妙想法。

* TODO 4chan：互联网的遗民
** 快速FAQ

A：为什么写这么一个博文？

Q：因为国内没什么人看4chan。这也就是一篇安利文吧。
可能大多数中文论坛，谈及4chan 的就是“臭名昭著的粪坑”，
或者是“网络暴力的根据地”；时不时也能看到几篇黑色幽默的“4chan笑话”。
用国内论坛类比，其形式为中国的“A岛匿名版”所借鉴；
然而就内容而言，其实更接近百度贴吧；包罗万象，有不少精品贴与亚文化，
除了4chan没有用户账户，人人都是anon（匿名者，anonymous)。

我喜欢百度贴吧，至少是以前的；五湖四海的网民们热心总结资源与教程，
相互之间谈天说地，或体现出每个人的人生轨迹，
堪称是中国互联网文化与精神的范本。
不论其中糟粕，贴吧也曾让我有所收获；
而接触 4chan 同样让我是收获满满。因此我希望写篇介绍文。

A：4chan 用户都是些什么人？
Q：不需统计，其用户画像多为英语圈的美国白人。
再加一条，就是用户多宅男。/a/（动漫版）是此处最大的版块。
总之，用户大约是歧视链的顶端，鄙视链的底端（weaboo）。
如果你混二次元，先补几部番能更好地理解 4chan，
虽说这里的用户是婆罗门扎堆。

** 翻遍小网站，你能得到什么
*** /a/ Anime
动画版，与动漫相关的各种东西。
然而并没有很多子版块，虽然其它版块普遍有大量子版块。

梦开始的地方。从中甚至产生了一部同人 Galgame。

*** /g/ Technology
科技版，实际上其内容面向程序员群体。
这一版块的用户鱼龙混杂，涉猎广泛，有各种常驻子版块：
- /dpt/：Daily Programming Thread，编程日常串。
- /fwt/：Friendly Windows Thread, 友好 Windows 串，
- /fglt/：Friendly GNU/Linux Thread, 友好 GNU/Linux 串，
- /flet/：Friendly Lisp & Emacs Thread，Lisp 与 Emacs 串，
  总有各种 SICP 的 meme 图。
- /csg/：Chink Shit General，国货垃圾佬综合。
- /pcbg/：PC Building General，电脑拼装综合。
- /wsg/：Home Server General，自建服务器综合。
- /hsg/：Home Server General，自建服务器综合。
- /ptg/：Private Tracker General，PT 综合。
- /psg/：Privacy & Security General，隐私与安全综合。
- /dmp/：Digital Music Production，电音制作。

一些紧跟热点的子版块：
- /aicg/：AI chatbot general，AI 聊天机器人综合。
- /sdg/：Stable Diffusion general，Stable Diffusion 综合。
- /vsg/：AI Voice Synthesis General，AI 语音合成综合。

以及一些产品的推荐：
- /tpg/：ThinkPad General，ThinkPad 天下第一！
- /iemg/：
- /ppg/：Pen & Pencil General，笔与铅笔综合。

值得注意的是，其子版块的一楼（sticky）总有很多免费资源供下载学习。
 /g/ 的置顶MOD串放出了/g/的维基，从而/g/也是 Gentoo Linux 的意思。
 置顶还有三个人的“神像”：
 TempleOS 作者特伦斯・A・戴维斯(TAD)
 《珈百璃的堕落》里[[][“看不起苹果粉”]]的萨塔妮亚(SKM)
 GNU自由软件运动的理查德・M・斯托曼(RMS)，

*** /jp/
"get out of /jp/."（魔理沙）

日本版，包括势力很大的东方众，龙骑士作品讨论，型月，
日本偶像、综艺、地铁以及niconico与音MAD等等。
*** /pol/ Politically *Incorrect*
政治不正确版。用户多右派。
*** /lit/ Literature
文学版。有各种书单推荐，包括古代语言学习。
*** /tg/ Traditional Games
传统游戏版。包括绘画，写故事，下棋等消遣。


* TODO vim：千斤顶
* TODO 《SICP》有感：计科非计算机
