#+title: 简短博文

#+hugo_base_dir: ~/Data/Pilrymage/blog/
#+hugo_section: post
#+hugo_auto_set_lastmod: t
* TODO Test :tag1:@category1:
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: my-third-post
:EXPORT_FILE_NAME: index
:END:
** 有一说一
Emacs是世界上最好的编辑器！
#+begin_src C
#include<stdio.h>
int main()
  {
    printf("Hello, world!");
    return 0;
  }
#+end_src


* DONE Emacs 搭配 Hugo 的个人博客创作    :Emacs:@Lisp与Emacs:
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: emacs-with-hugo-blog
:EXPORT_FILE_NAME: index
:END:
参见：[[https://zilongshanren.com/post/move-from-hexo-to-hugo/][子龙山人]]，[[https://emacs-china.org/t/topic/5427][Emacs 中文社区串]]

作为一款文本编辑器，Emacs 的上限是肉眼可见的极高：定制水平很大程度上影响了编辑器的外观及能力。

上一次 Emacs 让我为之惊叹的是即使是在终端的输入，而内置的输入法真的也能在其中运作！
当然是因为 Emacs 的 TUI（终端界面）是通过GUI渲染的，然而这就能给终端赋以超越 vim 的能量。
vim 并非不能使用内置输入法，然而 Emacs 才是为大而全的应用而生，在ipad的终端里写文章不再是梦。

或许这也让我这个 Emacs 新人对 Emacs 狂热粉多了一分感同身受吧。爱好 Emacs 的大多是非常看重自己工具流的定制化。
因而当我找到一套适用于 org mode 的博客生成方案时，我不禁再次对 Emacs 社区的大佬们肃然起敬。

** 什么是 Org mode?
Org mode 是一个同 Emacs 绑定的软件包，也指这个软件包所操作的标记文本： org 文件。

可以用 markdown 文件来类比 org 文件， org 就是 organization （组织）。
markdown 文件有 Typora、 Notion 等等编辑器，将其渲染成网页上展示的形式。

而 org 文件主要跟 Emacs 一起使用，拜 Emacs 的海量文本编辑功能所赐，
org 的编辑器非市面上任何一款编辑器所能比拟。
比如直接从文本生成博客，敢问其它编辑器做得到吗？！

** 博客搭建
参见：[[https://gohugo.io/getting-started/quick-start/][Hugo quickstart]]、and [[HTTPs://gohugo.io/hosting-and-deployment/hosting-on-github/][Host on Github]]

Hugo 搭建非常快捷。上次尝试搭建博客还是在 Windows 上用 Hexo ，在 Github Pages 发布上要死要活。
这次跟着教程，花个 5 分钟就能开本地服务器了。 Github Page 也有适用于 Hugo 的 Action。

绑定个人域名有点麻烦，要在 DNS 提供商引导一个 CNAME 记录，
闲话一句，这也是我没用 Netlify 的原因，因为在应用里添加不上域名，显示已被占用，
它大概要让我把 DNS 记录全迁移到 Netlify 自己的服务器才行。（是我哪里弄错了吗？）

Github Actions 就是一个持续集成（CI），对新人而言最大的优势就是仓库也是 Github 的。
这之后只需 git push 就能更新博客，剩下的已经自动化。
** Emacs 与 Hugo 导出功能
参见：[[https://ox-hugo.scripter.co/doc/quick-start/][ox-hugo quickstart]].
Hugo 支持 org 格式作为博文，然而其渲染支持不比其 markdown 渲染器好。
更优的做法是让 Emacs 将 org 格式转化为 md 格式， 然后交给 hugo。
这里使用 Emacs 的 ox-hugo 包实现转化。

*** 安装
doom emacs 的 package.el：
#+begin_src emacs-lisp
(package! ox-hugo)
#+end_src

*** 配置
用 ~#+hugo_base_dir~ 指定 hugo 的根目录
默认的主题，ox-hugo会直接把 md 文件生成在 content/posts 里，可以直接跳到下一节。
如果你用的主题使用了不同的目录以及 Hugo 的 [[https://gohugo.io/content-management/page-bundles/][Page Bundle]], 如[[https://stack.jimmycai.com/writing/markdown][stack]]主题，
可以用 ~#+hugo_section: post~ 指定博文放在 content/post 里，
用 ~:EXPORT_HUGO_BUNDLE: my-first-blog~ 与 ~#+export_file_name: index~
形成一个名为 my-fist-blog 的文件夹，包含正文部分的 index.md 。

*** 导出
使用 ~org-hugo-export-wim-to-md~ 函数导出。该函数有快捷键，但是与 doom emacs 不兼容。
因为 org 的 todo 对应 hugo 的 draft 状态，只有先将博文设为 done 才能导出。
然后就可以用 ~hugo server~ 检查输出了。
** 结语
写个五分钟，这篇博文就已经部署好了，咱充分享受到科技的便利。
其实这篇也没有什么自己的东西，只是不完整地总结了一边前人的知识。
然而比之以前用 Windows 的 Git 命令行强行部署 hexo ，半懂不懂，个人觉得算是巨大的进步了。

学计算机的，果然还是要有一个 Linux 系统，免去众多的闲杂烦恼。
而遇见 Emacs， 虽说是学 Linux 的附带收获，却实在是我的一大幸事，它能不断满足我的奇妙想法。

* TODO 4chan：互联网的遗民
** 快速FAQ

A：为什么写这么一个博文？

Q：因为国内没什么人看4chan。这也就是一篇安利文吧。
可能大多数中文论坛，谈及4chan 的就是“臭名昭著的粪坑”，
或者是“网络暴力的根据地”；时不时也能看到几篇黑色幽默的“4chan笑话”。
用国内论坛类比，其形式为中国的“A岛匿名版”所借鉴；
然而就内容而言，其实更接近百度贴吧；包罗万象，有不少精品贴与亚文化，
除了4chan没有用户账户，人人都是anon（匿名者，anonymous)。

我喜欢百度贴吧，至少是以前的；五湖四海的网民们热心总结资源与教程，
相互之间谈天说地，或体现出每个人的人生轨迹，
堪称是中国互联网文化与精神的范本。
不论其中糟粕，贴吧也曾让我有所收获；
而接触 4chan 同样让我是收获满满。因此我希望写篇介绍文。

A：4chan 用户都是些什么人？
Q：不需统计，其用户画像多为英语圈的美国白人。
再加一条，就是用户多宅男。/a/（动漫版）是此处最大的版块。
总之，用户大约是歧视链的顶端，鄙视链的底端（weaboo）。
如果你混二次元，先补几部番能更好地理解 4chan，
虽说这里的用户是婆罗门扎堆。

** 翻遍小网站，你能得到什么
*** /a/ Anime
动画版，与动漫相关的各种东西。
然而并没有很多子版块，虽然其它版块普遍有大量子版块。

梦开始的地方。从中甚至产生了一部同人 Galgame。

*** /g/ Technology
科技版，实际上其内容面向程序员群体。
这一版块的用户鱼龙混杂，涉猎广泛，有各种常驻子版块：
- /dpt/：Daily Programming Thread，编程日常串。
- /fwt/：Friendly Windows Thread, 友好 Windows 串，
- /fglt/：Friendly GNU/Linux Thread, 友好 GNU/Linux 串，
- /flet/：Friendly Lisp & Emacs Thread，Lisp 与 Emacs 串，
  总有各种 SICP 的 meme 图。
- /csg/：Chink Shit General，国货垃圾佬综合。
- /pcbg/：PC Building General，电脑拼装综合。
- /wsg/：Home Server General，自建服务器综合。
- /hsg/：Home Server General，自建服务器综合。
- /ptg/：Private Tracker General，PT 综合。
- /psg/：Privacy & Security General，隐私与安全综合。
- /dmp/：Digital Music Production，电音制作。

一些紧跟热点的子版块：
- /aicg/：AI chatbot general，AI 聊天机器人综合。
- /sdg/：Stable Diffusion general，Stable Diffusion 综合。
- /vsg/：AI Voice Synthesis General，AI 语音合成综合。

以及一些产品的推荐：
- /tpg/：ThinkPad General，ThinkPad 天下第一！
- /iemg/：
- /ppg/：Pen & Pencil General，笔与铅笔综合。

值得注意的是，其子版块的一楼（sticky）总有很多免费资源供下载学习。
 /g/ 的置顶MOD串放出了/g/的维基，从而/g/也是 Gentoo Linux 的意思。
 置顶还有三个人的“神像”：
 TempleOS 作者特伦斯・A・戴维斯(TAD)
 《珈百璃的堕落》里[[][“看不起苹果粉”]]的萨塔妮亚(SKM)
 GNU自由软件运动的理查德・M・斯托曼(RMS)，

*** /jp/
"get out of /jp/."（魔理沙）

日本版，包括势力很大的东方众，龙骑士作品讨论，型月，
日本偶像、综艺、地铁以及niconico与音MAD等等。
*** /pol/ Politically *Incorrect*
政治不正确版。用户多右派。
*** /lit/ Literature
文学版。有各种书单推荐，包括古代语言学习。
*** /tg/ Traditional Games
传统游戏版。包括绘画，写故事，下棋等消遣。


* TODO vim：千斤顶
* TODO 看山不是山：解构方法用于任意一门学科的学习
** 序
简而言之：

看山是山是建构；

看山不是山是解构；

看山又是山是重构。

第一句的山是个概念或者是个表面，而第三句的山则是个系统。

——知乎用户“螺旋真理”在“如何理解「看山是山，看山不是山，看山还是山」的三层境界？”下的回答

** 认识一个学科的过程与后现代话术

一个人的学习一门课程的过程，同时是其一生求学十数年的缩影；
义务教育阶段给予人以基本的三观理性与社会运作的逻辑，此时由家长与老师耳提面命的指导；
大学则给予人审视反思自己所学的批判性思维，对自己身边的一切有所怀疑与思考；
而博士以及更深的研究者将会在一个方向上尝试用理性胶粘起众多的知识，
形成自己的“脚手架”，其百尺竿头者最终会为学科的大厦上添砖加瓦，更进一步。

从小学到博士，二十多年时间，耗费精力甚巨。
幸而我们暂且不需批判教材知识，更不急着投身学科建设。
然而我意识到，学习一个学科，总是可以用所谓“建构－解构－重构”的方法来深入。
要而言之，就是“螺旋式上升”的认知吧。

*** 感性认识

*** 打倒感性认识
* TODO Windows 重装扩C盘的故事，以及Archlinux 重装 grub 引导
** Windows 一事
我的电脑是 Windows + Arch 双系统。
某次抱怨 Windows 的 C 盘只有 60G 容量太小，分给 D 盘的空间太大，
于是果断删 D 盘，C 盘大大扩张。
———结果不知如何，电脑的管理员权限挂掉了。
可能也与我之前把一些环境变量写到 D 盘有关系。

由于大多数上次重装时软件都放在了 D盘 ，现在则是完全用不了。
用不了管理员权限，连rufus也用不了，也烧录不了重装盘。
幸好进入安全模式还能用管理员权限，还是老老实实地重装了系统。

** Archlinux 的抱怨
重装还好，结果重新启动，就不由分说的入了 ~grub rescue~ 。
好家伙，Windows 的事，grub 搀和什么？这也只能再烧一个 Archiso 盘来救场。

*** btrfs
照着 [[][archlinux 简明指南]]做的 btrfs 文件系统，回滚非常好用而不怎么要操心。
然而挂载就费点力了，主要单受过安利而没读过 btrfs 文档，而挂载又有一堆选项。
幸好第一轮折腾没有出事，老老实实找到指南来挂载。
ext4 的挂载要容易挺多。。。

*** /boot/efi 挂载一事
记不清是要把 EFI 分区挂在 /boot 还是 /boot/efi 了，也因此栽了大坑。
现在稍微明白一点 grub 加载 efi 的道理了：安装 linux 内核会把 img 文件放在在 /boot 里，
而 ~grub-mkconfig~ 会寻找这些 img 文件，做成 menuentry 项。
至于不会自动放出引导文件的系统，如 Windows，
有 os-prober 在 EFI 分区里寻找引导文件，Windows 就是efimgfw.efi。
我的EFI分区挂载在 /boot/efi，有子目录 /boot/efi/EFI 包含 Windows 等系统的引导文件。

一个坑是，指南说用 Windows 自己建的 EFI 分区，又说用 /boot 直接做启动分区挂载点，
结果 Windows 的分区默认 100M 大小，有时候 grub 装不进，有时候 linux 的 img 文件装不进。
用 /boot/efi 挂载， linux 的 img 文件装在 /boot 下，实际上是根目录（主分区）的一部分，这就装得下了。

os-prober 由于某种原因，报错 ~error mkdir /var/lock/dmraid/~ ，然后检测不到 Windows。
我没有头绪；有几个贴子说是自己的 fstab 没更新，挂载不对。
我最后直接手写 grub.cfg 文件了。就是要找到上面所说的 efimgfw.efi。

想通这一点大约折腾了一晚上4个小时加早上2小时。

*** fstab 与自动挂载
一个小知识，因为 /etc/fstab 也重做了，结果外挂的硬盘没有自动挂载。
要自动挂载也 +非常容易+ ： ~blkid /etc/<编号>~ 导入 /etc/fstab，
然后保留UUID，+格式与其它行相同即可+ 。
一个 ntfs 格式的外挂硬盘，可以同时用于 Windows 与 Archlinux 双系统的资源共享。
不过主要是 Archlinux 可以直接访问 Windows 的全部内容，Windows 和 ext4 不太对付。。。

linux 挂载后发现硬盘奇妙的变成了只读状态。这其实又是一个点：
需要使用开源 ntfs-3g 读写 ntfs。
按[[][官网]]说，fstab 不仅要改该盘格式为 ntfs-3g，还可以添加 uid 和 gid 开放权限。
我照教程添上了 uid 等等，才可以读写，结果原本看不清的文件名变得正常了。
——原来这是表示只有读权限的吗！可是以前也都可以用阿。

** 最后
照着教程装好的 Archlinux ，大约不能表示自己多么擅长 linux 。
一些小事故，足以让人看到自己和 linux 运维的水平差异。。。

成为一个不合格的系统管理员吧。

* TODO Windows 小技巧汇总
** Windows 安装
*** 推荐版本
个人用主力机，建议用 Windows 10, 支持时间长。
- Windows 10 IoT LTSC
- Windows 8.1 Embedded
- Windwos 7 POS Ready

*** 烧录软件
- Rufus (Windows)
- dd (Linux)

*** 小建议
一个电脑分两个盘是好习惯，这样重装 C 盘系统就不用搬运 D 盘资料，
D 盘还可以留一点装便携软件：重装后可以用里面的便携版本软件。
** Windows 装机
*** 正版激活
- KMS_VL_ALL
*** 专有软件
**** MS Office
**** Adobe 全家桶
*** 软件工具
**** 软件包管理器
- Winget
- Chocolatey
- Scoop
**** 实用工具
- 7-zip
- Everything
- geek uninstaller
**** 开发者工具
- git, msys, ssh
**** 多媒体
- vlc
- mpv
- nomacs
**** 互联网
- firefox
- tor
- thunderbird
**** 社交聊天
**** 开发者工具
**** 开发者工具
**** 开发者工具
* 学各种表音字母的心得
学习各种语言，第一步往往是先认字母表，然后学习发音。
这也很正常：听与读是绝对必要的，而读又往往依赖于听到的发音。
而且语言的书写体系绝大多数是表音的，因而花点闲工夫就能学会各种语言的读法与写法的规律。
在别人面前装模作样地写点“外语”，算是小小技能，足以秀别人一手。
比如，你知道“”读作“”，

本文就是作者自己在学习书面体系到发音的过程的一点经验。
面向希望快速了解一门语言的书写体系的朋友。如果愿意接触了解多门语言，效果更佳。

** 从何谈起？
众所周知，表音字母所构成的书写系统应该是见到就会读的。
最大的反例就是英语；单词“ghoti”可以读如“fish”，同时符合寻常单词的“发音规律”。
英语单词表音不规则，这里选择假定各位对义务教育级别的英语有所掌握。

不能看到即读出的，也可以是表意的汉字。比起英语更加吃日积月累。
非母语人学汉字绞尽脑汁；好在看到这一篇文章的各位，汉字水平大约不会差到哪里去。

我自己的经验有时需要一点日语基础，只需有掌握五十音的水平。
为何要求五十音基础？因为我的学习方法，一言以蔽之就是“转写”。
那么，这里就是我认为日语作为转写语言的优势：
1. 五十音的发音算是少的。每个人都能较快上手。
2. 五十音的辅音与元音交织有冗余，比如“ka,ki,ku,ke,ko”用了五个不同字母，
   而非一个辅音字母配一个元音字母，从而方便重复练习，建立印象。
3. 日语的“片假名化”比英语的拉丁化要好认。英语因为吸收了太多语言反而转写意义不大（即不规则表音）。

当然五十音的发音也还是少了，一些语言特有的发音得有意识地补充。
此时，英语转写更像一种“音标”，可以做不同语言间的发音参考。
另外，诸如音调，重音位置等细节，不同语言或有其规范，我的学习中没有关注这一部分。
以下的学习大约遵循以下套路：先了解某种语言的发音特点，再用其日语转写来理解字母表。

** 日语——五十音
大多数人学日语，却连五十音都没怎么入门。
这里权当作自己学日语经验的一部分作介绍。
[[][五十音图]]

请读几篇[[https://res.wokanxing.info/jpgramma/writing.htm][tae kim 的日语指南]],
然后尝试将几个英语单词转写作日语，然后可以是几个句子，然后是一整篇文章。
你完全不需要知道日语的任何单词；只要有英语单词就可以。

如果手头上有一本英语教材或单词书，转写可以玩一节课。
改成平假名再改成片假名，然后自己读几遍，体会一下“日式英语”的感觉。
一个小细节是，日语和英语全是浊音，汉语全是清音，这样日语发音也不会被汉语带偏。

在汉化组与母语人士看来，这就是“片假名地狱”；
然而单用于学习五十音的话，这的确很简便。

** 韩语——谚文
比起日语，韩语将元音和辅音区分开来，还有一个“韵尾”的部分。


** 希腊语——希腊字母
希腊字母在数学里大量使用。另一方面，拉丁字母是从希腊字母中派生的。
因而，希腊字母用英语转写更为方便。另一方面可能是我想象不出日语是如何说希腊名字的。

当时我刚好在读《奥德赛》，书尾有希腊人名的中文对照。
心血来潮后花了一个晚自习的时间，边查英文字典，摸清了希腊人名到英文翻译人名的关系。
另一个对我影响较大的内容是[[][希腊字母表歌]]。竟然和英语字母歌差不多么？

** 拉丁语——拉丁字母
到处都是拉丁字母，英语、法语、意大利语、西班牙语…

其实长得相似，来源也一样而发音不同的几门语言最难学其发音。读的人总是想当然。
但是拉丁语发音有很简单的类比：当作日语罗马音读就没错。
除了拉丁语的字母 r 是可能被读作大舌音。

** 俄语——西里尔字母
俄语所用的西里尔字母表有33个字母，
其中有一点拉丁字母，一点希腊字母，还有一点自创字母。

** 德语

** 阿拉伯语——阿拉伯字母
阿拉伯字母的28个字母和拉丁字母以及汉字几乎毫无关联。
因此最要紧的是看懂各种“蝌蚪文”是怎么区别开来的。
维基教科书上介绍了一种金字塔形的字母排序。

** 印地语——天城文
